#+TITLE: 1940 Meeting Commentary

* 1940 Meeting commentary by Kent OP Bull
*** Main Discourse
**** Chapter 7
***** [[7:7][Verse 7]]
The definition of the word "above" is key and critical to any interpretation
of this verse, let alone this meeting. One sense of "above" is in the sense
of a scalar quantity of knowledge with respect to a particular subject or area. 
If one being or intelligence possesses in a subject a greater quantity of 
knowledge relative to another being or intelligence it could be stated in a 
comparative sense that the being with greater knowledge is in a higher place of 
knowledge than the being with the lesser knowledge.


Another interpretive sense of the word "above" here could be a reference to a
divine or godly power. This interpretation could be particularly important to
the viewpoints or positions who want to derive their validity from an appeal to
authority, especially divine authority.


A third interpretation of the word "above" here is as an indicator of relative
position in an authority or knowledge hierarchy. A hierarchy typically includes
roles of decision making authority or roles of responsibility that are segmented
or compartmentalized within each level of the hierarchy according to a set of
rules. A hierarchy can be a useful tool to control activity within a domain of 
existence. The nature of hierarchy established indicates what rights, privileges,
or prohibitions a member of the hierarchy have with respect to the other members 
of the hierarchy. Members placed above other members in a hierarchy may be given
greater rights, privileges, and responsibilities within a domain of existence.
Inferring the inverse position of one "below" another one may deduce that a 
hierarchy member below another member has lesser rights, privileges, and 
responsibilities with respect to a given domain than the hierarchy member or
members one is placed under.

Hierarchies of decision making authority and property ownership are particularly
important to ecclesiastical, economic, and family bodies.

***** Verse 8
Elden seems to be invoking an assumption of divinity here by stating the rules he
deduced in his mind reflect the order of divinity or the heavens. His statements
seem to lead the audience to interpret the word "above" as heaven or a divine
body of beings. An alternative way to view this statement is that the word 
"above" could apply to a group of men who develop a higher system of social order
by the reasoning of their own minds. 

Weaknesses of this argument include emotional appeals and the lack of strong
reasoning. The 7:2 reference to searching for a thousand years can be taken as
presentational hyperbole useful for making dramatic, emotional effect. 
Furthermore it jumps to conclusions rather than itemizing premises and arriving 
at a sensible conclusion. 7:7-8 uses a very ambiguous term "above" to provide
interpretive opportunity for Elden to make claims to divine credibility for the
idea he is presenting. The surrounding context does seem to make clear that the
term "above" in this context refers to divine authority or at least divine 
knowledge. The challenge of using the term "above" in this way becomes more
pronounced as the document progresses to use the term "above" to refer more to
a hierarchy composed of men rather than solely a divine authority. It could be 
argued that the hierarchy of men is an extension of divinity when properly 
organized yet therein lies the rub. The link between a hierarchy of men and a
hierarchy of Gods, or divine beings, is the point of primary contention of any
religion or group claiming divine authority.
**** Chapter 8
***** Verse 3
This claim of some law decreed is simply stated as fact with no supporting 
premises provided as proof or explanation. There may be an implied premise based
on the idea that mankind usually has no direct knowledge or experience of the
divine if the divine is defined and thought to be something that is other-
worldly or otherwise unknowable or less knowable than the phenomena of our
present experienceable existence. 
Further, there are no definitions or allusions to other sources where the
terminology of this verse may be understood or correctly perceived or received
by the audience. Overall this verse leaves much to be wanting.
**** Chapter 9
***** Verse 1
This verse may be perceived as conflating two possible interpretations of the
word above, one being knowledge based and one being location based. Interpreting
the word "above" as knowledge based could bring one to see the one above oneself
as above in the sense of a higher level of understanding or knowledge. 

Alternatively, interpreting the word "above" as representative of a heavenly,
otherworldly, or other-dimensional location or place can lend itself to an
authority structure based on establishing a hierarchy between a location
above and the present location of the earthly world. This verse seems to take
expressive advantage of binding both of these meanings to the word "above." 

Whereas one may distinguish these two interpretations of the word "above" such
an act can lead to significantly different interpretations of the Law Of 
Satisfaction or Law Of One Above Another. Separating the requirement for divine
authority derived from some location other than earth opens up interpretation
of the LOS or LOOAA to being a mere knowledge sharing mechanism rather than
a command and control mechanism.
**** Chapter 17
***** Verse 1
This allusion to a great sacrifice can bring to mind many things.
***** Verse 2
Thus begins the justification of total control.
***** Verse 6
There seems to be a great deal of pre-selling of this condition before 
occurrance of any substantive discussion of the technique which produces the 
claimed condition of peace and harmony. The presence of this pre-selling may be
taken as psychological suggestion conditioning the audience emotionally for 
acceptance of the technique prior to a full knowledge or understanding of the
technique regardless of the efforts or sacrifices necessary to perform correctly
the technique Elden alludes to.
**** Chapter 20
***** Verse 2
This could be seen as taking advantage of the psychological property of scarcity
common amongst human beings as well as that of authority.
**** Chapter 21
***** Verse 3
Does this not sound very deterministic? Sure, there is choice involved, yet when
taking psychological pressures into account does this not seem like something
commonly attributed to Satan in that Satan is said he had a plan where everyone
would always succeed? Sure, Satan is said to force people to do right. Yet,
just a few verses prior the mention of severe penalties indicates a degree of
force. 
**** Chapter 27
***** Verse 3
Stating "there must be as much force and power in the remedy as in the evil" seems
to readily imply the remedy is or can be very forceful and powerful. Once again
this seems like a sales tactic. Elden must have forseen the resistance to the
ideas he was about to put forth regarding the Law of God.
**** Chapter 28
***** Verse 1
This verse seems to prey on the scarcity and exclusivity psychological properties
of the human ego and could be seen as making an appeal to the ego's desire for 
glory, legacy, and status.
***** Verse 3
This statement seeds ideas for a guilt and punishment complex to put 
psychological pressure on an individual to conform as well as social pressure 
to conform due to the audience members knowing one another and associating daily
and frequently one with another.
***** Verse 4
Really? Are you kidding me? Such a blanket statement. 
**** Chapter 31
***** Verse 4
This is an assumption, a conclusion Elden jumped to. He seems to rely on one 
using spiritual intuition to establish the claim of 31:1 and 30:2. To use the
word know generally implies some sort of experience. Other than listening to 
Elden make these claims what has the audience experienced to come to this claimed
knowledge of what the Lord expects? Simple spiritual witness or testament? Or 
is there some reproducible, verifiable evidence indicating the will of God in
this matter?
**** Chapter 32
***** Verse 1
A claim of knowledge without supporting statements; a conclusion jumped to.
***** Verse 2
This takes advantage of the desire of human beings to belong, to conform, to not
be alone. To be one is to be in company with others rather than alone, is it not?
**** Chapter 33
***** Verse 3
There is so much talk of what is done to the one above by disobeying this law. 
This seems to be possibly characterized as a pity party being thrown by Elden
for himself and Marion Brown for having to deal with pushback by the other 
members ostensibly from a lack of comprimise likely due to strict claims to
authority and demands for unquestioning obedience. It might be more believable
if there was some talk about what this does to the one below other than a mention
to some vague punishment or penalty.
**** Chapter 41
***** Verse 1
Likely the most overt authority grab in all of scripture I have ever read or come
across. Any rational being would likely only accept a bond of such a claimed
bonding power after receiviing a personal testament of this so-called Law of God.
Elden has only given an intellectual exercise here in attempt to establish
validity and credibility of this Law of God. Sure, those in the audience may have
felt or claimed to have felt the Spirit of God as a spiritual experience 
testifying to the truthfulness of this Law of God. However, the spiritual 
experience of the audience does not translate through the text, or even to the
days following the meeting date this Law of God was given.

What validation and testing methods are given to the individual to determine for
himself or herself whether this is a true law? Is it anything experential or is
it merely a spiritual witness that is required? Is one willing to cede 
sovereignty over oneself due to one or two experiences of a spiritual witness?
For me, not likely, depending on the nature and the impact of the spiritual 
witness or experience. If I am to submit to this so-called Law of God and cede
control and sovereignty over my being to it's authority structure in order to
comfort my mind and spirit I would have to have some repeatable discipline I 
could follow in order to verify the divinity and truthfulness of this law and
it's claimed authority structure. 
**** Chapter 57
***** Verse 57
This seems to be designed to relieve those below of the personal responsibility
to know for themselves whether their actions will bring about a good or bad 
result. It seems to absolve those below of any guilt. So, if those below are not
guilty when following instructions and those above are also not guilty for 
following instructions all the way on up the line then who is it that is guilty
or responsible for the results, especially when things go bad? Is the entire
hierarchy innocent? That seems a very convenient escape for the ego, just 
following instructions.
Who is responsible? Elden might say it doesn't matter, he might say that 
assigning blame or responsibility is a concern that those below should not
concern themselves with. He might even go as far as to say that assigning blame
could be clouding that blood or influence.
**** Chapter 58
***** Verse 3
Here Elden invokes an all too perfec enemy, Satan. He is such a perfect enemy that
whenever an individual steps out of line this enemy is there to take advantage of
every misstep. This could be an incredible psychological and emotional burden to 
bear.
**** Chapter 61
***** Verse 7
Elden makes an implicit claim here that he knows the character and disposition of
the Lord. It seems a far more helpful act would be him giving his audience a way
to come to an experential knowledge of the character and disposition of the Lord
for themselves rather then having to rely on Elden for an explanation or 
interpretation.
***** Verse 8
Here it appears Elden is giving those above a justification for ignoring those
below. This could explain much of the communication difficulties and challenges
I have observed in the Order to date.
**** Chapter 62
***** Verse 6
This seems like a silver bullet, an all in one, an easy solution to getting 
through all of life's sufferings, to trust in this idea of the Law of God.
**** Chapter 64
***** Verse 2
It seems difficult to imagine God as being so emotional and having such a 
tempestuous heart as to have his good feeling towards a being to be knocked
out by a little floundering. That does not sound Godly at all; that sounds like
Elden's opinion of god. Maybe that is how Vesta and Charles treated and taught 
Elden in the home. That could explain the origin of this idea in Elden's heart.
***** Verse 5
Elden seems to be very petulant or reactionary here. The stress of dealing with
people for five years from 1935 to 1940 must have really gotten to him.
**** Chapter 66
***** Verse 2
Some seem to be more equal than others.
**** Main Discourse Summary
