#+TITLE: Davis County Cooperative Society Documents

* 1940 Meeting
** Chapter i Part of opening prayer given by Clyde Gustafson, Brother 2 
*** i:1
We ask that Thy name might be glorified in the earth, that this people's hearts
might be opened up and they might understand what you desire this people to do to
gain their salvation. 
*** i:2 
We ask if there be anyone that desire in their hear that they receive a testimony 
of the divinity of this work; we ask Thee, our Father in Heaven, that Thou grant
them a testimony this day.
*** i:3  
We ask Thy blessings to rest upon that Servant, Brother 1.
*** i:4
Wilt Thou cause that Thy Spirit will be over him, that he might bring forth the 
things which Thou hast asked him to bring forth this day?
*** i:5 
We thank Thee for the revelations Thou hast given unto us, and we thank Thee 
that Thou has thought enough of us to send these messengers here unto this earth
to give us these instructions.
*** i:6
We pray thou wilt bless our flocks and herds; take away our hearts of stone and
give us hearts of flesh.
*** i:7 
Teach us Thy spirit, and grant us the discernment of spirits.
*** i:8 
We ask these blessings in the name of Jesus Christ, amen.

** Main discourse given by C. Elden Kingston, Brother 1
*** Chapter 1
**** 1:1
Brothers and sisters, I surely thank God for this day.
**** 1:2  
The time has come, brothers and sisters, when I have the privilege of taking the
burden and moving it out a little further and placing it upon a few more.
**** 1:3 
This burden, brothers and sisters, which has taken some of us nearly to the
grave, and would have if the Lord had not cut things short.
**** 1:4 
I hope, brothers and sisters, everyone is waiting with outstreched arms to 
receive all you can take, because there is plenty.
**** 1:5
You should, each and every one of you, rejoice exceedingly, and I know you will,
to have this privilege.
**** 1:6 
There is going to be the greatest responsibility that has ever been put on men
and women in the flesh, that is going to be laid on you today.
**** 1:7
You can't comprehend that, but I assure you, every one of you - if you will let
your mind run along with the spirit this morning - you will have more than I have
ever told you, or that you have expected there would be.
**** 1:8  
There will be none of you who will say you feel you should have gotten more, not
one of you.
**** 1:9 
As I told Brother Bert yesterday in the afternoon meeting, I wanted to prepare
him for something, and I have to prepare practically all of you this morning.

*** Chapter 2
**** 2:1
Brothers and Sisters, these things have been going forward here for five years,
and now at the beginning of the sixth year there are seven men and seven women
here who are prepared.
**** 2:2 
Now I don't know why it should be just seven of each.
**** 2:3 
You brothers and sisters are not going to have the privilege of hearing the names
of these brothers and sisters, you must be prepared; get prepared and be careful
of your steps so you won't faint.

*** Chapter 3
**** 3:1
Let us take our minds back to the end of yesterday's meetings.
**** 3:2
Let us start building again.
**** 3:3 
Let us be as sure as we can that we understand correctly, and be sure to not
misunderstand; let us have patience enough to be willing to give ourselves what
time we need, so that we will not be found talking or saying things or
misinterpreting words which might be brought forth this morning.
**** 3:4 
One of the main things that was stressed yesterday - one of the main facts we
must take hold of - is the binding of Satan, is it not?
**** 3:5
The binding of Satan within this group, within this order.

*** Chapter 4
**** 4:1
Now, brothers and sisters; there has been a dirty stream of water running right
through us.
**** 4:2
That stream has been dirty because WE HAVE BEEN MAKING IT DIRTY, not because
someone on the outside has been throwing in the filth; but because we never had
the knowledge, we never had the power, we never had the good rope to put around
the ram's neck.
**** 4:3
Because we had the rotten rope and had to keep tying him up - that is the cause
of the filth that has been streaming around us.

*** Chapter 5
**** 5:1
ALL THAT MUST BE STOPPED TODAY; EVERY BIT OF IT!
**** 5:2  
That is, unless you are displease God and your brothers and sisters, because you
are going to have a rope you can use, and if you DO NOT USE IT, it is going to be
your own fault and own neglect, every one of you.
**** 5:3 
Because just as soon as we, ourselves quit polluting this stream it is going to
clear up; clear up faster than any stream you ever saw - clear up and it will
remain pure just as long as we will keep this filth from us.
**** 5:4 
That is all it is - the lowest kind of filth which is parting us from eternal
life, or the path that leads to eternal life - that is all it is.

*** Chapter 6
**** 6:1
Now what do we have here that is representing this filth we are pouring in?
**** 6:2
We have all the evils of the adversary that he is continually pouring through us,
that is what it consists of.
**** 6:3 
Brothers and sisters: If we cease pouring this filth in the stream, we must pick
out everyone of these ills, put them all together in a bundle in such a way that
this rope will fit around them good and snug, so none of them will slip out, and 
then stick it in a place where it isn't going to bother.
**** 6:4
How are we going to do it?
**** 6:5  
Where can we go to find a remedy for these ills?
**** 6:6  
Many of us have come here practically every Sunday; been edified greatly during
the last five years, and yet, we, at this time, are unprepared to accomplish
that thing.
**** 6:7 
Where will we go to get the remedy for it?
**** 6:8
Can we go to the history of any people that we have record of?
**** 6:9 
No, we can't.
**** 6:10
There is no record that has been handed down to us of any people that explains 
how we can do these things.
**** 6:11 
We do have records of people who have done it and been successful, but we have
not the rules, the laws that made it possible for them to do these things.
**** 6:12
We don't have them, but brothers and sisters, if we are going to get anywhere,
we will have to get them.

*** Chapter 7
**** 7:1
There is only ONE PLACE you or I, or any other good saint can go to get these
things
**** 7:2 
We can spend a thousand years roaming around going here and there, and at the
end of that time we have spent, we will all - every one of us - come to the
conclusion there is only one place where we can get those remedies, and get
them so we can understand them and do them.
**** 7:3 
If we get a remedy for an ill in a way which we can't understand, it isn't going
to help us until we are able to understand, is it?
**** 7:4
It is of no advantage to us unless we can use it.
**** 7:5
We can't, under any condition or consideration, get the results of that remedy
until we can understand how to use it.
**** 7:6 
That is where we are going to get today.
**** <<7:7>>
I am sure every one of you will agree with me, that the one place where the 
remedy for all these ills is, is above; the only place we can get it from is
above.
**** 7:8 
That is the only place where these laws are being put into practice - where the
results are being obtained - is above.
*** Chapter 8
**** 8:1
Brothers and sisters, if we could all just get one glimpse, it would be worth a
thousand words.
**** 8:2 
Just one peek for a part of a second; how much would it be worth to us?
**** 8:3 
But there is a law decreed, with very very, few exceptions that through our
progress along the road of eternal life, those things above us are held as
mysteries, and as we go along, the keys and the powers that we receive, that we
obtain - are for the Kingdoms, powers and beings of lower orders, and so we
must be content with that fact; we must realize that that law was wisely put
there, and it has been wisely lived up to and will be wisely lived up to.
*** Chapter 9
**** 9:1
Now as I say; we mus thave these things; keys, remedies brought to us from 
above - from some place where they have them.
**** 9:2
We can't go in a post office and get medicine; we can't go in a drug store and 
get letters either.
**** 9:3
All fruits of all kinds must come from the places which are there to produce
those fruits.
*** Chapter 10
**** 10:1
Now then, one of the first things I want to throw before you is the Law of God.
**** 10:2
The Patriarchal Law of Abraham, the law of the patriarchs; the law that has not
only been stressed to them, but it has been stressed to us as Latter-Day Saints.
**** 10:3
I want you to remember there is a difference there, and remember those laws
which have come to your konwledge before this are only little parts of this Law
I am talking about now.
**** 10:4
It is the same Law I talked about yesterday when I brought out these three
things:
**** 10:5
YOUR SUCCESS IN THE LAW IS BECAUSE OF YOUR BEING ABLE TO MEET EVERYTHING THE WAY
THE MASTER DESIRES.
**** 10:6
YOUR FAILURE IN THE LAW IS BECAUSE OF YOUR OWN INDIVIDUALISTIC PECULIARITIES.
**** 10:7
INTELLIGENCE WHICH CANNOT BE GOVERNED BY THAT LAW IS WORSE THAN CHAOS.
**** 10:8
Now that is the Law.
**** 10:9
The Law that everything hinges around, EVERYTHING.
*** Chapter 11
**** 11:1
Now, brothers and sisters, the results of this meeting is going to go out just
the same as the waves go out when you drop a rock in the water; it has to go
just the same as these waves msut go when you drop the rock in water.
**** 11:2
As these  things go out, they are to be known before all people.
**** 11:3 
I am not telling you to advertise it; you will find yourself in the hands of
Satan if you do it and are not careful; you must only do it under the direction
of the spirit of the Lord.
**** 11:4
So be careful, and as these things go out the are to be known as the "GOLDEN
RULE".
*** Chapter 12
**** 12:1
Some of the master minds of the earth have, in their ideals, taken the way
people should get along together.
**** 12:3 
Their highest ideal was where there was no friction and no trouble - everyone
treated their brothers and sisters as themselves, and peace abounded.
**** 12:4
They called that condition - or referred to it - as the GOLDEN RULE:
**** 12:5
But where are there ANY OF THEM that have been able to put it into practice?
**** 12:6
NONE, because they do not have the key to the PLACE WHERE IT IS.
**** 12:7
So remember, when you come to these places where you meet these things; remember
the label you must place on it is the "GOLDEN RULE": DO NOT FORGET THAT.
**** 12:8
This morning as I started out I called it the Law of God.
**** 12:9
I am calling it right so you, as a people here, will more readily understand
what I am trying to get at.
*** Chapter 13
**** 13:1
Before this meeting I have wondered, and I have studied for words that I might
use to get this meaning across to you, because those things are not talked 
about; we have never before heard them, and I yet feel I might not get words so
I will get these things across to you.
**** 13:2
But I know with the help of God all things are possible.
**** 13:3
Now then, we are talking about the Law.
**** 13:4
I am going to add the LAW OF SATISFACTION.
**** 13:5 
The law where if it were possible to see above us; if it were possible to see
individuals there - we would see them come together - we would see them part;
we would see them work together.
**** 13:6
We would see them part with absolutely no friction, backbiting, cross words,
strifes or envyings present.
**** 13:7
That is the same condition we must get in.
**** 13:8
How is that possible?
**** 13:9
Because they understand the LAW OF SATISFACTION.
**** 13:10
In other words, there are rules and methods which govern all these contacts, all
these meetings; everything that goes by, and they are not hard to remember 
either - the are just as simple as that.
**** 13:11
Just that easy to apply and they are applied because those individuals have the
power of it; they have the knowledge of it, and they are put under great penalty
if they evade these laws, and they all rejoice in the fact that that condition
is there.
**** 13:12 
They rejoice in the fact that everything is plain; that everything is clear, and
everything is in such a manner so that none of them need err in the least 
degree - none, NOT ONE.
**** 13:13 
In other words, the path is marked out in front of every individual.
**** 13:14 
This path has two sides on it, imaginary sides.
**** 13:15
These individuals walk up this imaginary path, although it is just as clear as I
am standing before you.
*** Chapter 14
**** 14:1
In a path that puts them in prison? No!
**** 14:2  
I would say, in a path that opens up ALL ETERNITY to them; all kingdoms, powers,
things of a lower order, and as they progress, all that comes in their line of 
duty.
**** 14:3 
We are talking about this imaginary path with two sides on.
**** 14:4
I am afraid some of you are going to interpret that as a path that holds you in
prison.
**** 14:5  
I hope you won't, but it is an imaginary path with two sides on.
**** 14:6
After an individual passes on, you look right behind him and see that both sides
are straight up, just like in front.
**** 14:7
In other words, that individual does not knock off the sides and leave a stony
trail behind.
**** 14:8
Now when this path is pointed out to you today, there will be many of you that,
when the Angels of God, and those who are watching over us examine our progress,
they will see that we have walked up our path and floundered along as we went,
knocking stones off the sides and our path is not clear.
**** 14:9 
That has to be expected, the best you can do you will do that.
**** 14:10 
I am telling you brothers and sisters, you are going to make mistakes the very 
best you can do, because those things are going to be in your trail.
**** 14:11
Showing absolute evidence that you have floundered around, although you have 
done your very best.
**** 14:12
You have knocked off the sides, run into the sides because it is the very
thinnest veil and you will be very, very lucky if you get back.
**** 14:13
In other words, we cannot take those chances if we think anything of eternal 
life; it isn't worth it.
**** 14:14
As I have said; this path is very closely connected and is some of the parts of 
the Law which I have brought before you - one of the parts of the "GOLDEN RULE."
*** Chapter 15
**** 15:1
Now another part of this Law, "THE GOLDEN RULE:" is the "NEW AND EVERLASTING
COVENANT."
**** 15:2
Now this covenant which you have in mind that I do not need to tell you about is
only a small part of it, and you go back to these covenants you have made and
you will find out right there it will tell you so.
**** 15:3 
The keys have always been there whereby we might; people might have taken hold
of them and gone up the ladder a little farther.
**** 15:4 
In other words, brothers and sisters, everyone of you who have made those 
covenants in the Temple have already made all of the covenants that you have the
privilege of making where a man in the flesh metes them out to you.
**** 15:5 
That is, unless you slip and fall and have to make some of them over if you are
required to.
**** 15:6 
Brothers and sisters; remember, even you folks who made those covenants in the
Temple;l you have already made all the covenants that you are ever asked to make
where a man in the flesh metes them out to you.
**** 15:7
A New and Everlasting Covenant is not a covenant of that kind.
**** 15:8
It is a covenant I have not the privilege of giving to you; and yet, everyone of
you who have made these covenants, you have promised to fulfill ALL THE RITES,
ALL THE RESPONSIBILITIES pertaining to the New and Everlasting Covenant - you
all know that to be a fact.
*** Chapter 16
**** 16:1
In other words, you did not have the privilege of making THAT COVENANT. 
**** 16:2
I want you to remember that and konw that to be a fact, and if you do not know 
how to make THAT COVENANT after this meeting, you are going to have to do some
fasting and praying.
**** 16:3
I am sure I know that everyone of you who are here can see the difference it 
would be, the difference there would be in the results we obtain from day to
day, working together if we were able to live that law of satisfaction, where
every time two of us came together, under any and all conditions, we would know
absolutely how to conduct ourselves so there would be no strife, no ill
feelings: None of those ills of the adversary present.
**** 16:4
If that condition existed we could all be building, instead of haveing to climb
upon our step again after being knocked down.
**** 16:5 
We could be building, instead of having to hold one of our brothers and sisters
to keep them from falling.
**** 16:6
We could be building, instead of worrying about all these ills that are going to
happen to a brother or sister; instead of saying if brother so and so acts so
and so, you will have to do so and so.
**** 16:7  
That has taken up a good deal of time, and I want to say that brother so and so
has been very faithful in watching those things and catching all those things as
they come along, and I surely appreciate it, and I know all you brothers and
sisters know I am referring to Brother 4, because that is the way the Lord 
works.
**** 16:8 
When such and such a thing has happened, Brother 4 has been there on the job,
and brothers and sisters, I surely appreciate it.
**** 16:9
Whenever I have told him about certain things, anything that was going to come
along, and if it came to a certain stage t obe there, he has been there, and he
has not acted too harsh either, not one bit, and I am right behind him in 
everything he has done - everything.
**** 16:10
Now, that should be greatly appreciated by all.
*** Chapter 17
**** 17:1
Now after we have partly imagined the difference in the results of our labors
and the energy that goes through our beings every day if it were possible for us
to take hold of that power in order for us to have our energy to keep what we
have already - we have to admit, brothers and sisters - that result - the 
greater result if necessary, is worth a great sacrifice.
**** 17:2
Is there any sacrifice that you or I can think of that will equal that result?
**** 17:3
No, not one.
**** 17:4
I could fast for two months if it took it for that, with God's help.
**** 17:5
I know I could go longer, if it was necessary and required in order to bring
this condition about.
**** 17:6 
I hope that none of you will let any straws lay in the road which will detract
from this condition, because we are indeed lessening the value of that result
very, very greatly, if we let some of these little straws stop some of these
wonderful blessings - wonderful results which will automatically go forth.
*** Chapter 18
**** 18:1
If it were possible for us to get only one peek, it would be worth a thousand
words of explanation - just one peek.
**** 18:2 
Now, coming to that very condition, the condition which exists among the Gods:
The condition which is comeing into this room today; we would see that 
everything that was done there came down from above, from the next one above the
individual which you have the privilege of seeing.
**** 18:3
Those instructions no matter how bitter - no mater the sacrifice it causes the
one below to make - you never see them frown or offer a contradictory word.
**** 18:4
Why? Because they have the knowledge and power that they know that their path is
plain before them, just the same as I hope it is going to be plain before you.
**** 18:5
*** Chapter 19
**** 19:1
Let us drop back to this NEW AND EVERLASTING COVENANT.
**** 19:2
I am going to have to jump around in the hopes that I will be able to explain a
little clearer this NEW AND EVERLASTING COVENANT.
**** 19:3 
As soon as you come to a knowledge of this law so that you understand it well
enough to do, (probably all of you won't here today) as soon as you come to a 
knowledge of all this law sufficient to do so, then you in secrecy, at the time
that the spirit directs you, get down upon your knees and make this NEW AND
EVERLASTING COVENANT with your God in Heaven.
**** 19:4
You don't need to say anything to anyone about it - you don't need to say 
anything to me about it - and you will find out it won't be very long until I 
will know ALL ABOUT IT.
**** 19:5 
You don't need to say anything about it to anyone else either.
**** 19:6
It doesn't make any difference whether I know all about it or not, or whether 
anyone else knows all about it.
**** 19:7
The thing that does make the difference is your works; the results of your 
labors; the results of the energy which goes through your being.
*** Chapter 20
**** 20:1
In other words, at this time when you make this covenant, you will have 
understanding enough within your being to know absolutely, without a doubt in 
your mind, that you understand this law well enough to know that, that law 
concerning you IS NEVER GOING TO BE CHANGED.
**** 20:2
Because you will know it well enough to know that there is NO OTHER LAW OR
CONDITION in existence of any other place that can even take you to first base.
*** Chapter 21
**** 21:1
Can you call that pure knowledge?
**** 21:2
If you can't you will never find it.
**** 21:3 
You will know that law well enough so that under all conditions, in all your
contacts with your brothers and sisters or anyone else, you will know before you
ever make that contact, the reactions which must come from your being.
**** 21:4
You will know that as I have explained to you, as brother 4 has followed - that
if someone else acts so and so, you will have to act so and so.
**** 21:5 
You will have that knowledge within you so you will have it right and what to
say under those conditions - because you will know.
**** 21:6
Now then, those are the things which you will know when you are prepared to make
that covenant, and I want you to remember that if you don't know those things
YOU ARE NOT PREPARED, and the spirit of the Lord will not direct you to make
that covenant.
**** 21:7
The spirit of the Devil might, if you allow yourself to be in such a condition
he might - but the spirit of the Lord won't.
**** 21:8
We will find it in all these things that the spirit of the Lord is our 
protection.
**** 21:9
he won't bring onto us anything that we are not prepared for.
**** 21:10
He will prepare us; strengthen our knees and shoulders so we can carry it.
*** Chapter 22
**** 22:1
Now we can imagine if we can go back up there where that law is in full force,
we will se there that the main duty of every individual, regardless of how high
a God can be - His main duty is to absolutely please the one above Him, or the
one that is placed there to give Him His instructions and directions from day to
day, and He does it, finding joy in the same - not only finding joy, but 
satisfaction and eternal life also. 
**** 22:2
That is what He finds.
**** 22:3 
THAT is the path of eternal life.
*** Chapter 23
**** 23:1
One of the main things of it IS TO BE ABLE TO ABSOLUTELY PLEASE THE ONE THAT THE
LORD HAS PUT THERE to direct you and help you and guide you.
**** 23:2
If you brothers and sisters can absolutely do that to the very fullest extent,
you can walk along this path and you can see the walls are still straight and
the sides have not been knocked off.
**** 23:3
Now that condition is JUST THE OPPOSITE to what we have here in the world today,
and also among us as a people to a very great extent, and it has been one of the
biggest burdens that has been felt here in the order - in that one condition
being absent and the opposite being present.
*** Chapter 24
**** 24:1
In other words, one of the most evil tools the Devil has is TO STRIKE THE HAND
THAT MADE HIM.
**** 24:2
And FOR HIS PURPOSE, THE VERY BEST TOOL THAT HE HAS IS TO GET US TO STRIKE THE
CHANNEL WHERE OUR LIFE COMES THROUGH, in other words, TO CUT OUR OWN THROATS.
**** 24:3
There is no quicker way to your death and my death than by striking the place by
which the Lord has designated for us to receive our spiritual life and our 
spiritual welfare, and when I talk of death, I am not talking of temporal death
either.
**** 24:4
I am talking about a spiritual death.
**** 24:5
That is one of the things he gets us to do if possible, is to strike in that
direction.
**** 24:6
He does not have to get us to worry about what is below us - that all takes care
of itself; but he gets us to working on those above us.
**** 24:7
He gets us to working on that chain; and brothers and sisters - what a sight we 
make up there - what a mess.
**** 24:8
We can't see how we clutter up things because it is just above our reach.
*** Chapter 25
**** 25:1
Now brothers and sisters; that is ONE ILL we absolutely must wipe out.
**** 25:2
We might wonder how it is wiped out among the Gods, how it is that hey do not do that?
**** 25:3
If that is one of the greatest evils that anyone can do here, is it not 
reasonable that one of the greatest punishments will be there for it?
**** 25:4
Can an evil be checked without having a punishment equally as large as the evil?
NO!
**** 25:5
Whenever you stop anything that is evil, you must have your remedy just as large
as that evil.
*** Chapter 26
**** 26:1
Now here today, just the same thing is happening as if I was to take you up into
Idaho over the Snake River and tell you we are going to dam that stream off.
**** 26:2
There isn't a one of you here that would say we can't do it.
**** 26:3
If you had your natural mind here, you would tell me we can't do what I tell you
we have to do this morning.
**** 26:4
Every one of you would tell me that.
**** 26:5
If we went there to that Snake River to dam it off; if that was an evil we had
to check, every one of you would know we could not dam that off if we had no
straw or machinery bigger than we would ever think of using: that is the same
with us.
**** 26:6
We have to have something we can't even think of handling; we must have the 
power of God with us to do it.
**** 26:7
We MUST HAVE the spiritual power of God.
*** Chapter 27
**** 27:1
If the lord directed us to go here and do that, we know we could go there and do
it, if he chose us to do it in that way.
**** 27:2
We can't do it unless God gives us the remedies, for those evils that are in
equal proportion to the evils to overcome.
**** 27:3
In the same way, what we have to use to dam that river off must be in equal
proportion to the river; so I say, brothers and sisters, the remedy for this evil
whereby Satan and his agents, even we ourselves, in times in the past, have used 
our energy to strike above; there must be just as much force and power in the 
remedy as in the evil.
*** Chapter 28
**** 28:1
I hope you are following along with me, as I have mentioned before, the 
responsibility that is going to be placed on each and every one of you is greater
than any responsibility which has ever been placed on any other men and women in
the flesh.
**** 28:2
I know some of you can recall some of the penalties that are opposite.
**** 28:3
Brothers and sisters; before I go any further I want to tell you that TODAY IS 
THE DAY that you here today are going to be subject to those penalties.
**** 28:4
Because you are going to have all the knowledge and understanding that you need
in order to be advanced far enough to put yourself in a condition so that THERE
IS NONE OF THOSE PENALTIES you won't be subject to - NOT EVEN THE GREATEST THAT
YOU CAN THINK OF.
*** Chapter 29
**** 29:1
Now brothers and sisters; remember I asked you yesterday how many of you knew
the Lord and how many of you knew the Saviour.
**** 29:2
How many of you know more about Him than those He gave those revelatiionis to,
where he said: "You do not come unto Me because you do not know me."
**** 29:3 
Now go back to this order that we have been thinking of and talking of.
**** 29:4
Every individual there, no matter what authority, standing or station he is in,
is responsible to the one above him in exactly the same way; he must please them
in exactly the same way as if that individual was the Saviour himself; or I will
go further than that.
**** 29:5
They must respect him and please him or her just the same AS IF THAT INDIVIDUAL
WAS THE HIGHEST GOD THEY KNEW OF.
**** 29:6
The influence of this highest God that they know of is there, and He requires 
that of those individuals who are acting.
**** 29:7
The same thing holds true with you and I; as we treat the one that is placed 
above us, we treat the HIGHEST GOD THAT WE CAN KNOW OF just the same, and it is
taken for the same all up the line.
**** 29:8
Those who are above us look down and see those individuals among us who don't do
that, or don't have a desire to do that.
**** 29:9
They are floundering along their path, and pretty soon they will throw themselves
out.
*** Chapter 30
**** 30:1
You and I CANNOT TREAT OUR BROTHERS AND SISTERS TOO GOOD, and if we don't treat
those above us the very best we know how, there is something wrong with us - 
SOMETHING RADICALLY WRONG.
**** 30:2
In other words, all our connections and associations with the one above us must
be met in exactly the same way as if the HIGHEST GOD was put there in his shoes.
**** 30:3
If we know that, we KNOW HOW TO TREAT THE SAVIOUR.
**** 30:4 
That is all we lacked before; we lacked the knowledge, and some of us were awful
neglectful in trying to find that out.
*** Chapter 31
**** 31:1
If that is what we must know IN ORDER TO KNOW HIM, is that of any value?
**** 31:2
Brothers and sisters; there is nothing that equals it, there is NOTHING: and I 
am telling you: THAT IS WHAT HE EXPECTS and that is what we must know in order
to know him - not only Him, but ALL THE OTHERS.
**** 31:3 
The Saviour is the mediator of this NEW AND EVERLASTING COVENANT.
**** 31:4
Now we know the Lord, in other words; WE KNOW WHAT HE EXPECTS.
*** Chapter 32
**** 32:1
Every one of us here knows this fact, without a doubt in their minds, that the
Saviour's Spirit penetrates everything, and when we talk about the Saviour we
know without a doubt THAT HE COULD NOT BE WITHOUT THOSE ABOVE HIM, so when we
talk about the Savior we are also talking about ALL THOSE WHO ARE ONE WITH HIM.
**** 32:2
When I talk about the Saviour, I talk about you brothers and sisters who are one
with him.
**** 32:3
IF YOU ARE ONE - THAT INCLUDES YOU TOO.
**** 32:4
Everyone who is in perfect harmony must be figured in, and they are a part of 
that power and influence, NO MATTER HOW SMALL A PART, they are a part of it.
**** 32:5
We know that spirit if we go to the scriptures; it is called the Spirit of
Christ, and it is not only HIS SPIRIT, but it is the SPIRIT OF ALL THE GODS ABOVE
AND BELOW, every being that is in line for Godship is what we are meaning.
*** Chapter 33
**** 33:1
All right; we all know that influence.
**** 33:2
His spirit penetrates everything, does it not?
**** 33:3 
Not one thing of any description does it leave out; even the dominions of Satan
are penetrated by that spirit and held in place.
**** 33:4
When we get to those dominions of Satan, we see that spirit is cloudy, dark and
gloomy.
**** 33:5
When we have that privilege of looking around with a spiritual eye, that is what
we see.
**** 33:6
That spirit is there, and holds those powers and dominions in their places, and
is clouded up in that condition; and, of course to the spirit or being who has
the spiritual eye to look around - as soon as they glance over and see that 
cloud, they know what is there, and they know with a clance what is there because
they know that all the influences that are where the spirit is - that spirit of
Christ, cause all things to move in harmony - it is clear, JUST AS CLEAR AS
CRYSTAL.
**** 33:7
There is no one throwing any mud into it, not one bit.
**** 33:8 
Not a bit of filth of any kind is being thrown into that straem, and so it is
absolutely, without an yexceptions, clear that is, for any length of time to
speak of at all.
**** 33:9
All right, my brothers and sisters, WHAT IS SPIRIT: IT IS THE MOST IMPORTANT
PART OF THE BEING OF GOD, OR INFLUENCE.
*** Chapter 34
**** 34:1
I am stopping here and jumping over again in hopes that I can make it clearer by
doing the same.
**** 34:2
I am jumping back to the straight and narrow path where every individual
absolutely pleased the one above UNDER ALL CONDITIONS.
**** 34:3
All these individuals, acting there in their proper place and sphere have the 
SPIRIT OF CHRIST - in other words, they are part of it.
**** 34:4
THEY ARE SPIRIT, THE MOST IMPORTANT PART OF THEIR BEING, is the INFLUENCE, THE
PURIFIED SUBSTANCE THAT flows through their veins, the LIFE-GIVING SUBSTANCE.
**** 34:5
Brothers and sisters; blood flows through your veins - blood flows through my
veins, - REMEMBER THAT, BLOOD.
*** Chapter 35
**** 35:1
We look back at these individuals in their proper places, one below another; we
pick out one individual; maybe he will be down on the line of one of these 
branches that I partly stressed yesterday.
**** 35:2
All those above that individual are, absolutely without any question of a doubt,
innocent as far as that individual is concerned, regardless of what they do.
**** 35:3
Just as long as they are in that line, they are ABSOLUTELY INNOCENT as far as
that individual below is concerned.
**** 35:4
If there are individuals up there that are floundering around, JUDGMENTS FROM
ABOVE take care of that EVERY TIME.
**** 35:5 
Individuals down below have other duties; they must take care of their own
responsibilities, things below them.
**** 35:6
So every individual above you or I, no matter who they are, what their names are,
or what about them; as far as you or I are concerned, THEY ARE ABSOLUTELY
INNOCENT.
*** Chapter 36
**** 36:1
Now then, we must look at the one above us in the same light as we look at the 
Saviour.
**** 36:2
In other words, the Saviour's blood is there, we are PART OF HIM.
**** 36:3
Brothers and sisters; THERE IS THE PENALTY - THERE IS WHERE INNOCENT BLOOD IS
SHED.
**** 36:4
When you understand that, and use your hand in the least degree AGAINST THAT - 
you don't have to take my life, or your brother's life, or anyone else's life,
all you have to do is CLOUD THAT BLOOD.
**** 36:5
That is all you have to do, that is every bit, AND DON'T YOU FORGET IT.
**** 36:6
All you have to do is some little thing which takes that spirit, or influence
which is bright and clear before you and put a cloud on it, and you are shedding
that substance which is superlating and is everywhere present.
*** Chapter 37
**** 37:1
We go to the scriptures or the Doctrine & Covenants, and we find there where it
says; "And assent unto My death." talking about spiritual things.
**** 37:2 
We know very well we will never have the power to go slay the Saviour. We know
that.
**** 37:3
We know He is too important and He is following His path too straight for the 
Lord to ever let us get in a condition where we might have that chance or
privilege.
**** 37:4
We know too, for someone to be in that class, if they had to do that in order to
become a Son of Perdition, we konw there would not be any Sons of Perdition.
*** Chapter 38
**** 38:1
What does it mean when it says: "and assent unto My death?"
**** 38:2
It means, consent or do anything that will put a cloud on His life influence
which is penetrating all things; to do this in any way, or even consent to any
other party which might be doing the same.
**** 38:3
We know when individuals find themselves in that condition, just doing little
things, just making a little cloud, it is very often easy for them to make a
bigger cloud, and very often they go the whole road because of their 
flounderings.
**** 38:4
We can see this remedy is large enough and powerful enough to take care of that
evil.
**** 38:5
It is the MOST POWERFUL REMEDY THAT CAN EVER BE USED, and which IS USED, and it
is so easy for us to come under it's clutches, SO EASY.
*** Chapter 39
**** 39:1
Brothers and sisters, many of you here HAVE SHED ENOUGH OF THAT BLOOD TO DROWN
THE CITY OF SALT LAKE ALREADY.
**** 39:2
There is a difference in your punishment based on and regarding your 
understanding, but there is no difference IN THE RESULTS OF YOUR ACTIONS. If you
were ignorant of these facts, and you did things to shed this bright, living 
substance that was superlating in your presence, and you did things to cloud
that up, you would be clouding that up regardless of your understanding: You 
would be clouding it up just the same as if you had a perfect knowledge of what
you were doing, but where the punishment comes, we cannot be held accountable
and punished in that degree until we get a full knowledge of that law, and then
our punishment is greater; but of course, the results are the same.
**** 39:3
The results when you or I do these things affect those above us in exactly the 
same way, regardless of our knowledge; affects those above us in exactly the 
same way regardless of our understanding.
**** 39:4
If we run an automobile into a telephone pole, it does not make any difference
what we know about that automobile, it breaks the automobile just the same.
**** 39:5
The same with anything else; if we do a certain thing with anything, what we do
determines the results, not what we know about it.
**** 39:6
But the punishment we get for doing those things is determined by WHAT WE
UNDERSTAND.
*** Chapter 40
**** 40:1
Now brothers and sisters; what about this authority, or all these keys which 
govern the actions of all of us connected with this law, THE LAW OF SATISFACTION:
The Law which stands up in the center and all others are hinged around it?
**** 40:2
All other things, all other connections to this law are regulated by keys of
power for certain other laws, certain other privileges and blessings; all these
other conditions, relationships of all kinds - keys of power.
*** Chapter 41
**** 41:1
If the Lord sees fit to give me the keys of power to do a certain piece of work,
and He sends His spirit to you and directes me to get you to help me, I have 
those keys of power, you are bound to me just the same as if I was the Highest
God in the Heavens, and you, if you can walk straight, will work with me in that
way.
*** Chapter 42
**** 42:1
Now you have all had keys of power, you all posses them at the present time.
**** 42:2
Every man here in this order who has a wife or family, has the keys of power from
God to govern that family; and if any individual of that family does or says
things which cloud that part of God, they are doing it to THE HIGHEST GOD THAT WE
CAN EVER THINK OF.
**** 42:3
That is what He expects and that is what He takes when we do these things.
**** 42:4
So, sisters WHERE ARE SOME OF YOU AT?
**** 42:5
Unless that is stopped, there are going to be many on the road to Perdition to
our sorrow, the sorrow of God.
**** 42:6
Because I am telling YOU, EVERY ONE OF YOU, THERE ISN'T a husband here who hasn't
the keys to that power, as well as the keys to the power of their stewardships in
other things.
**** 42:7
Every one has proven worthy and you have them at the present time, and you will
keep them as long as you live up to the knowledge which you have.
*** Chapter 43
**** 43:1
I hope we will take those things and carry them off like men and women, shoulder
them up, live them; because if you don't, brothers and sisters, it doesn't make
any difference how bad I feel; how much sorrow or tears any one can shed, you 
must go that road.
**** 43:2
There is no one, NO GOD SO HIGH THAT HE CAN STEP IN AND CLOSE YOU OFF, because
that is there; and it is there for people who do these things, no one else, AND
THE ROAD OF PERDITION MUST BE STRICTLY KEPT INTACT.
**** 43:3
It doesn't make any difference who slips, flounders and fall; you or I, or even
those above us, if they slip into those clutches THEY MUST GO THE ROAD, 
absolutely no exceptions of any kind.
*** Chapter 44
**** 44:1
Every one of you stewards has at the present time, the keys of power which have
been given to you concerning your stewardship by Brother 4 or myself, whichever
one it was, or Brother 2.
**** 44:2
The last word that has come from one of us to you, no matter which one of us, 
stands at the present time until you receive further instructions.
**** 44:3 
That is where your keys of power lie, and that is youro responsibility at the 
present time.
**** 44:4 
Brother 2 at the present time, for the benefit of all of us, has the keys of
power pertaining to the shoe shop; not only in part, but ALL.
**** 44:5
Whatever he directs you to do regardless of what you do concerns his stewardship,
whether it is through Number 11 or any of the present places of business, 
Brother 2 will direct them, and they will live up to what he directs regarding 
the customers, also regarding us as brothers and sisters in the order.
**** 44:6
The requirements he might make in respect to us getting our shoes repaired there,
we must live up to, if any.
**** 44:7
If the Lord gives me anything to give to Brother 2 to follow out in his 
stewardship, he is going to be very diligent in seeing these other brothers 
understand it and fulfill it.
*** Chapter 45
**** 45:1
Now there will probably be some of you who won't know just where you are at for a
while, and I won't be a bit surprised either; but do the best you can to get in
line as quickly as you can get in place.
**** 45:2
I want to tell you, it doesn't make any difference whether it is Brother 4 or 
myself, if either one of us, or any one else, providing they have the keys of 
power to come to you, I hope you will respect all the same.
**** 45:3
Always remember where you are at.
**** 45:4
I know if Brother 4 went up to Kaysfille and told you to do certain things, if I
went up the next day and told you to do just the opposite, I know Brother 4 would
be able to stand that test.
**** 45:5
I know if it comes to that concerning any one of you individuals, you will be 
expected to stand it too.
**** 45:6
In other words, you won't be able to stand anything of that nature; you can't
unless you know where you are at; unless you know your place, or your position in
line, you will not know what to do.
**** 45:7
But it isn't always necessary to know the standing of your brother above you.
**** 45:8
Lots of times there will be questions.
**** 45:9
And I want to tell you that up to this time, I have been myself, instructed and
directed by at least six, and I have never yet been told which was above the 
other, and I don't know - and I don't know why I don't know.
**** 45:10
But I do know this, that I have those instructions and I have been able to take
them, with the help of God, in a way so there was no confusion.
**** 45:11
Now if we can do that, we know that is satisfactory, do we not?
*** Chapter 46
**** 46:1
Concerning this one fact I have already brought before you; if I would say this
isn't fair to me - I want to know where you fellows stand, I would have innocent
blood on my skirts just as soon as I opened my mouth.
**** 46:2
There would be no other results, absolutely, and I thank God that He has brought
this knowledge to me to prevent me from doing that, and I hope that you, every 
one of you, will feel the same way about it.
**** 46:3
I hoep that you will thank Him for this knowledge and power that has come here
today, and that you will be able to cease from doing those things, absolutely.
*** Chapter 47
**** 47:1
Now, is that path any plainer to you?
**** 47:2
You bet it is.
**** 47:3
Is it getting anywhere near the condition so you can see how even a fool can
follow it?
**** 47:4
I hope you can see now where it might be possible that a fool might be able to
follow it.
**** 47:5
Now another example which may happen here, or it may happen up above; because we
are coming to these conditions, these things are coming here today - remember 
that.
**** 47:6
Say Brother 2 goes to Brother Ren and says: "Brother Ren, you do so and so." And,
by the way, we will say Brother 2 received that from me and I received it from
above.
**** 47:7
I will say to Brother 2, you tell Brother Ren to do so and so.
**** 47:8
That act seemed to be very foolish to Brother Ren, and he says to Brother 17: 
"Brother 2 has instructed me to do so and so; It appears to me it is very 
foolish, doesn't it to you?"
**** 47:9
Even though Ren feels that way when he speaks those words, he is shedding that
blood, ABSOLUTELY, HE IS SHEDDING THAT BLOOD.
**** 47:10
He is beginning to shed that blood BECAUSE HE IS CROSSING THAT INFLUENCE WHICH
BROTHER 2 LEFT THERE.
**** 47:11 
What should Brothe r17 and Brother Ren do under those conditions?
**** 47:12
This is what they will do when they properly understand it; they will confess
their ignorance to what Brother 2 has left there for them.
**** 47:13
They will confess they do not know why Brother 2 has left this there, and they
will be able to hold themselves in the straight and narrow path.
**** 47:14
I have confessed my ignorance to you a number of times concerning a lot of 
things, and I have confessed my ignorance to you because I was ignorant of that
fact, and when I confess my ignorance to you of a fact, I want you to know I AM
IGNORANT OF IT.
**** 47:15
There are a lot of those details I don't need to know all about; and if I had to
know all about them, my mind would be so taken up I would not have room for what
should be there.
**** 47:16
I don't need to know all those details.
**** 47:17
All I need to know in regard to you is WHAT I SHOULD TELL YOU.
**** 47:18
AND WHAT I SHOULD TELL YOU AS LONG AS I AM FOLLOWING THE STRAIGHT AND NARROW 
PATH, BOTH BEFORE AND BEHIND YOU.
**** 47:19 
ALL I HAVE BEEN TOLD TO TELL YOU TO TELL TO SOMEONE ELSE.
**** 47:20
When I tell you these things you ask me "why?"
**** 47:21
I have to confess my ignorance to those things because I am as dark as the ace
of spades concerning the reason for it, ABSOLUTELY.
*** Chapter 48
**** 48:1
I am going to be continually ignorant of those things; I am going to be just as
ignorant as the Lord makes me.
**** 48:2
Not because I want to slight any one, but because I have only twenty-four hours
a day, seven days a week, and 365 days a year, and you or I can only accomplish
so much.
**** 48:3
That is all we can do, so we must include that which the Lord places before us 
and be ignorant of those other things which we haven't room to assimilate.
**** 48:4
That is all we can do - is fill up the space and time that we have; under any
condition, that is all.
*** Chapter 49
**** 49:1
Now then, when this work first started, those of us who were privileged to be
here first were required to sacrifice high salaries; salaries which gave us
everything that we needed in our homes so that our homes could be well kept and
in good shape, and we were required to go down below all things; give up all 
these things, even to the condition where we did not even have a bed in the
house.
**** 49:2
All of our fine clothing, furniture, and all these things were disposed of in one
form or another as God directed.
**** 49:3
We did not do that just because the Lord wanted to have some fun with us.
**** 49:4
We did that because it was part of the Law which we must abide by; which we all 
must abide by and go through in order to prove us; make us as pillars which can
stand; put us in a condition so we will take hold of these powers and follow them
right up.
*** Chapter 50
**** 50:1
All these things are coming back which we sacrificed.
**** 50:2
If we will be patient, they will all come back as the Lord directs.
**** 50:3
But up until this time we haven't shown very much patience; we have reached out,
taken some of these things before hand, and we who have done that have lost a
part at least, of a very important blessing through the same.
**** 50:4
You have clouded that influence to yourself to a great degree.
**** 50:5
And not only to yourself, but to your brothers and sisters who have had to be in
your presence.
*** Chapter 51
**** 51:1
I know all of you will agree that the proper way to receive any of these things
is as the Lord hands them out.
**** 51:2
And we will admit that if we rush Him in the least degree, we are on dangerous
ground.
**** 51:3
We might think that sounds funny to have the privilege of rushing the Lord, but 
I want to tell you, THAT PRIVILEGE IS ALWAYS OURS.
**** 51:4
ALWAYS THERE, AND NEVER TAKEN AWAY.
**** 51:5
That is one of the easiest ways for us as individuals to have the privilege of
floundering, is by doing that very thing.
*** Chapter 52
**** 52:1
Brother 2 might come to me and say: "Here, Brother 1; it looks like it is all
right to put in another shoe shop."
**** 52:2
When Brother 2 does that, he as well as everyone of you, must be careful so that
you get the honest opinion which I have for you; because if you crowd me, I am 
going to make it fit YOUR IDEA.
**** 52:3
I am going to METE IT OUT BEFORE TIME, and that is the condition upon which I am
here among you.
**** 52:4
I want you, every one of you, to know what I am doing.
**** 52:5
I don't want you to come and get things before hand and not know what is 
happening.
*** Chapter 53
**** 53:1
If Brother 2 follows that path; walks it straight and leaves it clear behind him,
when he comes to me he will realize, if he pushes me I will give it to him before
hand.
**** 53:2
He will realize that if he gets it exactly as the God above him gets it, I will
have it for him without crowding me in either one direction or the other.
**** 53:3
He mus be sure that he does not do that; absolutely, if he isn't sure, he comes
to me and gets what I have for him in that way, and he will never know whether he
has gotten it as the God above me desires or not.
**** 53:4
There will always be a doubt in his mind whether he is acting in the right time 
or not, and if he isn't acting at the right time, he is CLOUDING THAT SPIRIT and
that LIFE BLOOD which is in his presence and assenting to the blood out of the 
same.
**** 53:5
Absolutely no other way to explain it, no other solution.
*** Chapter 54
**** 54:1
He is floundering around along his path and that little thing, no matter how 
small, it will lead to ANOTHER, and first thing he knows, if he follows that
spirit he will be outside of his path and he will be very lucky if he ever has
the privilege of coming back.
*** Chapter 55
**** 55:1
That path is still plainer, is it not? Still plainer.
**** 55:2
I want to say, brothers and sisters, to every one of you; if you get - and if
you are sure of what you are doing - you must get your instructions in that
very way, so you will be sure you have not influenced the one who is to get
those instructions in either one way or another, because that same thing holds 
good with you, even to your little children; that is included.
*** Chapter 56
**** 56:1
Now where are we at?
**** 56:2
We all look around and see where there is a good deal of that blood has been
clouded in that way, because we have not been willing to make a certain
sacrifice as long as the Lord expected us to; but we have insisted that we get
this and get that, and we have gotten it to our condemnation.
*** Chapter 57
**** 57:1
Now enough of this law has been opened up to you so that you know where you 
stand.
**** 57:2
Enough of it has been opened up to you so that you can see that it might be
possible for that Law to lead to eternal life, has it not?
**** 57:3
Is there anything else any of you have to compare with that?
**** 57:4
You can hunt and search for a hundred years, and you won't find anything that
can come to first base, because you can see your protection in being able to
hold yourself in that path.
**** 57:5
You can see where there is no pitfall for you to get into if you can walk 
straight and keep from floundering around.
**** 57:6
There is none, NOT ONE, as long as you stay on that path, and stay between two
walls; all pitfalls are on the sides, every one.
*** Chapter 58
**** 58:1
Those of you who have had the privilege of making some of these covenants which
were mentioned yesterday; you will remember that Satan, the Devil; he came along
after certain ones had received certain instructions from God.
**** 58:2
He said; "If you don't keep God's Commandments, you are in my power."
**** 58:3
In other words, if you or I cannot stay on that straight and narrow path, we
automatically find ourselves in the power of the Devil, going about doing his
will and fulfilling his purposes.
**** 58:4
Automatically, there is no other result and no other solution; we have to 
ABSOLUTELY be in his power if we don't keep ourselves in the right path.
**** 58:5
Just as plain as day, we have to be in one or the other influence.
**** 58:6
If we step out of one influence the other influence is there already.
**** 58:7
And so, brothers and sisters; if you or I, or any individual fails to keep the
commandments of God which are binding upon any one of us, regardless of whether
we are avisitor here today or not, we automatically are in the power of the 
Devil.
**** 58:8
We can't help ourselves, no other condition can be there.
**** 58:9
No other solution to that problem; it has to be that way, just as sure as you 
and I are here.
*** Chapter 59
**** 59:1
In other words, when we do these things to cloud this spirit around us, that is
the Devil's influence there that comes and clouds things up.
**** 59:2 
When we come and make these clouds we are making a condition there that is just
like the Devil, and that condition automatically switches in that cloud.
**** 59:3
There is no other influence there to come.
**** 59:4
The spirit of God WON'T DO IT, although the spirit of God is there making it
possible for that other influence to come there; MAKING IT POSSIBLE FOR THE
DEVIL TO COME THERE: We are under Satan's power and dominion.
*** Chapter 60
**** 60:1
I don't want anyone of you to think I have told you ALL ABOUT THIS LAW, or all
about this NEW AND EVERLASTING COVENANT, or all about ANY of these things.
**** 60:2
I don't want any one to think I have told you one-tenth, even though I have 
taken up a lot of time here.
**** 60:3
I want every one of you to realize - you visitors, as well as you who are members
here - regardless of whether you ever join this order or not; IT IS YOUR 
RESPONSIBILITY TO HOLD TO THESE THINGS; prepare yourselves to understand ALL THE
LORD HAS FOR YOU TO UNDERSTAND concerning these truths in the way which I have 
explained, by keeping yourselves in this path, STRAIGHT AND NARROW.
**** 60:4
That is the way through me, Brother 4; Brother 2, or whoever it might come 
through.
**** 60:5
That is the channel which you must hold to if you gan the things concerning 
ETERNAL LIFE.
**** 60:6
SO, PREPARE YOURSELVES, KEEP ON PREPARING YOURSELVES for what the Lord might 
have for you, or through whatever channel He might send it through to you.
**** 60:7
The Lord can do WHATEVER HE PLEASES concerning these things, and I am not going 
to rebel against that either.
*** Chapter 61
**** 61:1
I hope all of you will understand and know He has those privileges and powers.
**** 61:2
He does what He sees is best, regardless of what I think or what you think, or 
anyone else might think, and those who are prepared with the power, knowledge
and understanding to control themselves - they receive it.
**** 61:3
THEY DON'T UNDERSTAND WHY.
**** 61:4
They must confess their ignorance to those facts.
**** 61:5
They must confess their ignorance.
**** 61:6
If God wants to keep you or me ignorant to a certain thing, HE DOES IT, and we 
must be patient and willing for Him to do that, because that is the quickest
waywe can act to cut ourselves off, BY QUESTIONING THE LORD, and saying: "If
you will do this a little different, I wil lbe able to do my part better."
**** 61:7
The Lord doesn't take it that way.
**** 61:8
Just as soon as He started taking direction below, He would start to flounder
around, and knock the sides off of His path, and He would find that He had lost
out, NO MATTER HOW HIGH A GOD HE WAS.
*** Chapter 62
**** 62:1
SOMETIMES WE FEEL WE CAN GET HIGH ENOUGH SO WE CAN'T FALL, BUT NO MATTE RHOW
HIGH A GOD IS ABOVE US, HE CAN'T GET SO HE CAN'T FALL.
**** 62:2
The more we learn about life, the more we find out it is worth; the more valuable
it is, and I say; THERE IS NO GOD OR BEING ANY PLACE WHO CAN'T STEP OUT OF HIS
PATH AND BE PUT OUT OF EXISTENCE IN THE TWINKLING OF AN EYE: Go back to Chaos,
in other words.
**** 62:3
We might think we don't have any chance - maybe we haven't.
**** 62:4
If we do certain things I KNOW WE HAVEN'T, no question about that, absolutely.
**** 62:5
WE HAVEN'T, not unless we are willing TO MAKE THE SACRIFICES IT IS NECESSARY TO
MAKE, in order to keep ourselvese in that straight and narrow path.
**** 62:6
If we are willing to do that, there is no blessing, no matter how great or small,
that path won't lead us to in it's proper time and place.
*** Chapter 63
**** 63:1
God loves you and I; if He did not, we would not have what we have today, and it
is pleasing to Him to give us all these things we enjoy, providing we get them as
He sees fit to give them to us.
**** 63:2
Just exactly the same way as you and I as parents might look upon our little 
children as we put them out before us.
**** 63:3
These little children, maybe they have powers within them to go way ahead of us,
but we are raising them up.
**** 63:4
When I look at mine, I see the yare doing their very best to please, and my whole
heart goes out to them.
**** 63:5
There is nothing I would not do for them; no sacrifice I would not make for them.
*** Chapter 64
**** 64:1
The same with you brothers and sisters, when I see you walking that path, 
straight and narrow, there is no sacrifice I won't make for you, just the same as
these little children.
**** 64:2
One of these little children, they can be good for a long time, say a month, and
when they start floundering around they can knock that feeling out of me that
took a month to develop; the same with each and every one of you with God.
**** 64:3 
The same with each and everyone of you with me.
**** 64:4
You can be faithful and serve very diligently and then come to a floundering 
place and knock all that in the head in two minutes.
**** 64:5
All that appreciation, all that love that you have knitted together with your
brothers and sisters - all that wich has taken ten years to bind and seal 
between you - in a floundering emotion YOU CAN KNOCK IT ALL IN THE HEAD IN TEN
MINUTES.
**** 64:6
I can; anyone can.
**** 64:7
How careful we ought to be; how necessary it is for us to keep ourselves in that
right path.
*** Chapter 65
**** 65:1
There is one more point I want to stress again, and that is the point concerning 
you and I as we go after our instructions, which I brought out by example of
Brother 2 when he comes to me.
**** 65:2
There is one thing which we, as individuals, must be very careful about, and it
is the one thing which spreads the load of this work out more evenly among all of
you so it isn't resting only on two or three; and that fact is, you are in great 
danger IF YOU CROWD THE ONE NEXT TO YOU.
**** 65:3
If you crowd the one above you, you are absolutely in great danger, because that
privilege is ther where if we crowd the one above us, WE WILL RECEIVE, and you or
I, or anyone else, acting in our proper place WILL GIVE IF WE ARE CROWDED, every
time.
**** 65:4
The more you crowd me the more I move.
**** 65:5
The more you crowd God - or any one else, THE MORE HE WILL GIVE, regardless of
whether it is best or not.
*** Chapter 66
**** 66:1
So, Brothers and sisters, be sure when you go to God, or anyone else, that you
are perfectly willling to receive what you desire, AND WHAT GOD DESIRES YOU TO
HAVE, at the time, place and season, and as He wants you to have it, so that
you will be able to remain in the straight and narrow path.
**** 66:2
That is a great responsibility, because you must always be diligent concerning
yourself in regards to that.
**** 66:3 
It is the easiest way to flounder there is, to rush, to PUSH SOMETHING A LITTLE
BIT FASTER THAN GOD KNOWS IS BEST FOR YOU, and when we don't understand be sure
we confess our ignorance to the fact and not find fault; not to take up our time
in CLOUDING AND SHEDDING BLOOD, but do our very best in our ignorance to find
the good parts, good points, and reasons for it being done in that way.
**** 66:4
You might have to study for two or three days, but brothers and sisters, if you
don't accomplish anything, that is better than stepping out of the path and
SHEDDING THIS BLOOD, a thousand times better even though you accomplish nothing
and just hold your own.
**** 66:5
If we are wise at all, we will at least hold our own, at least.
**** 66:6
Remember also, each and every one of you brothers and sisters here; also all out
in the world, any place, must do the same if they get to these blessings; THEY
MUST GET IN THIS PATH.
*** Chapter 67
**** 67:1
Remember, I am in this path; I am subject to God the same as you.
**** 67:2
I am equal with you; I have the same responsibility and I must take care of mine
the same as you do if we both succeed - absolutely, and I want to tell you that I
can rush those above me if I choose.
**** 67:3
I can, YOU BET I CAN.
**** 67:4
That gate is open there, so if I want to I can.
**** 67:5
But I ask God to help me continually, to give me knowledge and understanding so
I won't.
**** 67:6
I ask Him to give me patience, charity, and all His qualities to help me so I
will be able to be patient, and remain in the place he desires me to remain, and
do the things He desires me to do.
**** 67:7
I want to say also, you can too, without going through me or any of the other
brothers and sisters.
**** 67:8
Lots of times brothers and sisters, those things have been done in ignorance;
you have not known it, just the same as this blood has been spilt - anyway, it 
has clouded up there, regardless of you or me understanding.
*** Chapter 68
**** 68:1
In other words, I have the same privilege as you have.
**** 68:2
You have the same privilege as I; the only difference, we are standing at 
different points.
**** 68:3
I am sure you have received more today THAN YOU EVER THOUGHT WAS POSSIBLE TO
RECEIVE, have you not?
**** 68:4
Now let us be careful; let us not make any missteps.
**** 68:5
We can now see how this power is opening up to us whereby it will be possible
for us to grow - GROW FAST.
**** 68:6
As others come to this knowledge and understanding, let us be careful that ALL
OF OUR STEPS ARE MADE IN THIS PATH without knocking the sides down, which in time
WILL PUSH US OUT.
*** Chapter 69
**** 69:1
I again thank God for what has happened here today, and I can't show my 
appreciation to Him too much for it.
**** 69:2
I will close, asking Him to continue to help us in these problems in the name of
Jesus Christ, amen.


