#+TITLE: Kent Bull Show Notes

* Youtube Channel Shows
** 2020-06-07 #32 Pain to Peaceful Connection. Possible? Practical?
*** Notes
**** Topics
- [[pain]]


* Topics
** Pain, Betrayal, and Connection <<pain>>
Have you ever been hurt by a friend or someone close to you? Did you tell that
friend how you felt after you were hurt? If you told them how difficult was 
telling them they hurt you?

How difficult would it be to tell your mother, your father, your pastor, many of
 your friends, that they hurt you?

What would be the benefit of telling them? Maybe they won't hurt you again in the
future if you tell them they hurt you. Or maybe they aren't really your friend.

Maybe your friend betrayed you.

There's an entire branch of psychology devoted to why people don't confront their
betrayers. Jennifer Freyd and Pamela Birrell wrote [[https://www.amazon.com/Blind-Betrayal-Ourselves-Arent-Fooled/dp/0470604409/ref=sr_1_1?dchild=1&keywords=blind+to+betrayal&qid=1591560241&sr=8-1][Blind to Betrayal]] which is a
great introductory book on this topic.

How is this relevant to us here?

As much as I want to stick around and help the Co-op evolve, help it grow into a
more welcoming, empowering, and freeing place first I must address the pain in my
being.

What do we all want in this life? Family, friends, wealth, prosperity, happiness,
meaning, faithfulness, completion, balance, harmony, success, fame, a lover, a
relationship with god?

In all of this what does it amount to? How does one become happy through any or
all of this? Connection. After all of my research, thinking, feeling, and 
existing on this planet I come back to the same word, the same concept. As of
late I add union to the mix, so unified connection, because union seems to imply
consent and respect from all involved parties.

Connection. Something wanted so endlessly, fully, and completely that some will
accept a counterfeit, an illusion rather than have no connection at all, or what
appears to be no connection at all.

And thus we find ourselves here today. As I gain greater clarity I see a hill I 
must take, ground I must cover in my own heart. I have to decide working through
the pain to get to connection is worth it. Maybe it is, maybe it isn't. When
you're in the arena, fighting the match you don't always know if you'll make it
through. What I can know is that I'll do my best regardless of what I face in the
arena.

Where did the pain come from?
