#+TITLE: Orlean Gustafson Diary Commentary

* Diary Commentary
** Summary
** Commentary of Entries
*** May 12, 1935 - p10
Orlean said Elden told her "Prophecy fulfilled by the Lord or by his servant is
the same." This could be one of the psychological justifications Elden used to
support his arguments of receiving keys, authority,  and inspiration from the
Lord.

*** May 14, 935 - p10-11
The use of numbers as titles for peope seems very odd, possibly dehumanizing.

*** April 1935 - p11
The phrase "choice spirit" seems to be used frequently.

*** June 25 1935 - p14
Orlean told of Elden's dream where he was in a wheel that turned while he stayed
upright. The wheel represented the priesthood. Could this dream be the origin of
the thought in Elden's mind that what he was doing was the stone cut out of the
mountain without hands that would grow to fill the whole earth?

*** November 1935 - p15
Orlean stated "The evil one has a duplicate for everything that the Lord has and
we must be able to judge between so we will not be deceived." This sort of 
thought likely came from Elden. How easy would it be for Elden to change the 
perception of an event or a thing by changing the label from duplicate to 
genuinely of god?

*** November 1935 - p19
Elden said "When we judge those above us we are stepping out of our place." This
looks to be part of how Elden was focusing his attention on those above and
below.

*** November 1935 - p20
Elden claims "It is natural for us to live according to the telestial glory 
because the earth is in its telestial state." He doesn't state any source for
this claim other than himself. Elden also claims the strange act of God is the
bringing of the Earth to a terrestrial state. I could see how Elden could connect
this to a law of oneness, or the Law of God, since the terrestial glory is one of
the moon where everything is at least one glory.

*** November 1935 - p21
Elden claims interestingly that "We can't expect the lord to have his purposes go
on as he did before because he is going to bring about his strange act and the 
world become terrestrialized." Another unsupported claim.

He also goes in an odd direction by claiming "The Savior's sacrifice does not 
reach any further than what we are able to do for ourselves." This seems to tie
the idea of a working faith to the Savior's sacrifice. No longer saved by grace.

Another claim is that "Our natural desires leads us to be separate and not one."
This seems in opposition to what psychologists and others know of the tendency
in homo sapiens to be tribal.

*** August 14 1935? - p23
Supposedly Ortell was baptized by fire and the Holy Ghost while up on the
mountain the prior night. He was be 16 at this time, Elden was 25.

*** October 9 1935 - p 31
Surprisingly Elden said "It is not our mission to go out and convert people.
It is our mission to preach the gospel to them. The elect will recognize this
work and the spirit will direct them here." This is very different than what I
have been taught my whole life. We have been taught we do not have missionary 
work at all. Yet here Elden says we are to preach. This is different.

Also, on October 10 Elden and others had impressions of moving to a different
valley. I never heard that before. Elden was born on October 10, 1909.

And somehow Brother 16, whoever that is, was shown Elden would become the one
mighty and strong and work under the direction of Joseph Smith. Is this 
happening the beginning of the idea that Elden was the one mighty and strong?

*** December 8 1935 - p42
Orlean talks of Elden striving for the gift of translation. I never before have
heard of that. Why was he striving for translation?

*** February 12 1936 - p51
Elden received a proclamation on Feb 10 1936 consisting of the belief of the 
Order which he and Marion Brown took to Bountiful for the mayor to accept it.
I never knew that before. Orlean said the proclamation of the order was
presented and sanctioned by the law of the land.

*** December 5, 1937 - p67
Elden stated, "Judgment in its rightful order comes from above and not from 
below." Later he stated, "If I die this property will go in my name throughout
the millenium." What? He questioned whether he would die? Did he think he would
live forever?


